Multiple changes.
* Removed: Unused file `src/kernel_wrappers/registered_wrapper.cpp` - we don't have a use for the subclass listing code (except perhaps in the example programs, at some later time); also removed a `util/` header which was only necessary in `registered_wrapper.cpp`
* Added: An example of the third mode of using the library: Obtaining a type-erased kernel wrapper via the factory
* Introduced a rather lame hack to ensure the static-initialization code for registering all kernel wrappers in the factory will not be dropped by the linker; this might not even be very portable and needs to be improved ASAP
* Script tweak
* Fixed: Default-initializing launch configuration limit objects to `{ }` triggered undefined-reference errors, so we initialize them with `{ nullopt, nullopt, nullopt }` instead, which has the same effect
* Added: The factory mechanism was lacking a method for producing a subclass which specified both the key and the construction arguments (as they may both be necessary)
* Fixed: Problems with the `cuda::registered::kernel_t` which were preventing its actual use for obtaining type-erased wrappers
* Fixed: When failing to find a subclass in a factory, we were using a mangled name in the exception's `what()`-string; we now de-mangle it using `util::type_name<T>()`.

diff --git a/examples/scripts/run-all-examples b/examples/scripts/run-all-examples
--- a/examples/scripts/run-all-examples
+++ b/examples/scripts/run-all-examples
@@ -5,10 +5,11 @@ examples_dir=${1:-examples/bin}
 echo -e "Running all example programs...\n"
 { cd "$examples_dir"; find . -type f -executable; } | while read example_file; do
 	relative_path=$( echo "$example_file" | cut -c3- ) # cuts out the initial "./" which find prepends
+	example_program_binary="$examples_dir/$relative_path"
 	echo -e "--------------------------------------------"
 	echo -e " Example: $relative_path"
 	echo -e "--------------------------------------------"
 	echo
-	"$examples_dir/$relative_path" && echo "SUCCESS" || echo "FAILURE"
+	$example_program_binary && echo "SUCCESS" || echo "FAILURE"
 	echo
 done
